version: 5.10.{build}
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
image: Visual Studio 2019
configuration: Release
platform: x86

after_build:
  - cmd: call install\build_package.bat elena.%APPVEYOR_BUILD_VERSION%-i386

build:
  verbosity: minimal
  project: elenasrc2\elenasrc2.sln 

artifacts:
  # archive the generated packages in the ci.appveyor.com build report
  - path: install\output\*.zip
    name: nightly-build

deploy:
  appveyor_repo_tag: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'ELENA Nightly Build'
  provider: GitHub
  auth_token:
    secure: mPwQDFEXhfxCz5d9Lzjl1kaRje/E3P1/jaQjWs7byEwEKsU+ljxIgIv5uKevaBXX
  artifact: nightly-build
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
