version: 5.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x86

after_build:
  - cmd: call install\build_package.bat elena.5.0.%build%-i386

build:
  verbosity: minimal
  project: elenasrc2\elenasrc2.sln 

artifacts:
  # archive the generated packages in the ci.appveyor.com build report
  - path: install\output\*.zip
    name: nightly-build

deploy:
  release: elena-5-0-$(APPVEYOR_BUILD_NUMBER)
  description: 'ELENA WIN32 Nightly Build'
  provider: GitHub
  auth_token:
    secure: mPwQDFEXhfxCz5d9Lzjl1kaRje/E3P1/jaQjWs7byEwEKsU+ljxIgIv5uKevaBXX
  artifact: nightly-build
  draft: false
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
