version: 6.0.2.{build}b
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
image: Visual Studio 2022
configuration: Release
platform: 
- x86
- x64

after_build:
  - cmd: call install\build_package_%PLATFORM%.bat elena.%APPVEYOR_BUILD_VERSION%-%PLATFORM%

build:
  verbosity: minimal
  project: elenasrc3\elenasrc3.sln 

artifacts:
  # archive the generated packages in the ci.appveyor.com build report
  - path: install\output\*.zip
    name: nightly-build

deploy:
  appveyor_repo_tag: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'ELENA Nightly Build'
  provider: GitHub
  auth_token:
    secure: 1rvO0d3X3m2IC6FheCCIRv4IdkOuahHvt1uZeph/H//jaPJkYZAx/McyxBghl8xT
  artifact: nightly-build
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
