#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: elenasrc2_elc_codeblocks_elc_lnx32 elenasrc2_elenart_codeblocks_elenart_lnx32 elenasrc2_elenavm_codeblocks_elenavm_lnx32 elenasrc2_elenasm_codeblocks_elenasm elenasrc2_tools_asm2bin_codeblocks_asm2bin_lnx elenasrc2_tools_ecv_codeblocks_ecv elenasrc2_tools_elt_codeblocks_elt elenasrc2_tools_og_codeblocks_og_lnx32 elenasrc2_tools_sg_codeblocks_sg_lnx32

elenasrc2_elc_codeblocks_elc_lnx32: 
	$(MAKE) -C elenasrc2/elc/codeblocks all -f elc_lnx32.cbp.mak

elenasrc2_elenart_codeblocks_elenart_lnx32: 
	$(MAKE) -C elenasrc2/elenart/codeblocks all -f elenart_lnx32.cbp.mak

elenasrc2_elenavm_codeblocks_elenavm_lnx32: 
	$(MAKE) -C elenasrc2/elenavm/codeblocks all -f elenavm_lnx32.cbp.mak

elenasrc2_elenasm_codeblocks_elenasm: 
	$(MAKE) -C elenasrc2/elenasm/codeblocks all -f elenasm.cbp.mak

elenasrc2_tools_asm2bin_codeblocks_asm2bin_lnx: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks all -f asm2bin_lnx.cbp.mak

elenasrc2_tools_ecv_codeblocks_ecv: 
	$(MAKE) -C elenasrc2/tools/ecv/codeblocks all -f ecv.cbp.mak

elenasrc2_tools_elt_codeblocks_elt: 
	$(MAKE) -C elenasrc2/tools/elt/codeblocks all -f elt.cbp.mak

elenasrc2_tools_og_codeblocks_og_lnx32: 
	$(MAKE) -C elenasrc2/tools/og/codeblocks all -f og_lnx32.cbp.mak

elenasrc2_tools_sg_codeblocks_sg_lnx32: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks all -f sg_lnx32.cbp.mak

clean: clean_elenasrc2_elc_codeblocks_elc_lnx32 clean_elenasrc2_elenart_codeblocks_elenart_lnx32 clean_elenasrc2_elenavm_codeblocks_elenavm_lnx32 clean_elenasrc2_elenasm_codeblocks_elenasm clean_elenasrc2_tools_asm2bin_codeblocks_asm2bin_lnx clean_elenasrc2_tools_ecv_codeblocks_ecv clean_elenasrc2_tools_elt_codeblocks_elt clean_elenasrc2_tools_og_codeblocks_og_lnx32 clean_elenasrc2_tools_sg_codeblocks_sg_lnx32

clean_elenasrc2_elc_codeblocks_elc_lnx32: 
	$(MAKE) -C elenasrc2/elc/codeblocks clean -f elc_lnx32.cbp.mak

clean_elenasrc2_elenart_codeblocks_elenart_lnx32: 
	$(MAKE) -C elenasrc2/elenart/codeblocks clean -f elenart_lnx32.cbp.mak

clean_elenasrc2_elenavm_codeblocks_elenavm_lnx32: 
	$(MAKE) -C elenasrc2/elenavm/codeblocks clean -f elenavm_lnx32.cbp.mak

clean_elenasrc2_elenasm_codeblocks_elenasm: 
	$(MAKE) -C elenasrc2/elenasm/codeblocks clean -f elenasm.cbp.mak

clean_elenasrc2_tools_asm2bin_codeblocks_asm2bin_lnx: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks clean -f asm2bin_lnx.cbp.mak

clean_elenasrc2_tools_ecv_codeblocks_ecv: 
	$(MAKE) -C elenasrc2/tools/ecv/codeblocks clean -f ecv.cbp.mak

clean_elenasrc2_tools_elt_codeblocks_elt: 
	$(MAKE) -C elenasrc2/tools/elt/codeblocks clean -f elt.cbp.mak

clean_elenasrc2_tools_og_codeblocks_og_lnx32: 
	$(MAKE) -C elenasrc2/tools/og/codeblocks clean -f og_lnx32.cbp.mak

clean_elenasrc2_tools_sg_codeblocks_sg_lnx32: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks clean -f sg_lnx32.cbp.mak

.PHONY: clean_elenasrc2_elc_codeblocks_elc_lnx32 clean_elenasrc2_elenart_codeblocks_elenart_lnx32 clean_elenasrc2_elenavm_codeblocks_elenavm_lnx32 clean_elenasrc2_elenasm_codeblocks_elenasm clean_elenasrc2_tools_asm2bin_codeblocks_asm2bin_lnx clean_elenasrc2_tools_ecv_codeblocks_ecv clean_elenasrc2_tools_elt_codeblocks_elt clean_elenasrc2_tools_og_codeblocks_og_lnx32 clean_elenasrc2_tools_sg_codeblocks_sg_lnx32
