#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all_lnx32: elc_lnx32 sg_lnx32 og_lnx32 asm2bin_lnx32 elenart_lnx32 elenavm_lnx32

all_ppc64le: elc_ppc64le sg_ppc64le og_ppc64le asm2bin_ppc64le

elc_lnx32: 
	$(MAKE) -C elenasrc2/elc/codeblocks all -f elc_lnx32.mak

elc_ppc64le: 
	$(MAKE) -C elenasrc2/elc/codeblocks all -f elc_ppc64le.mak

elenart_lnx32: 
	$(MAKE) -C elenasrc2/elenart/codeblocks all -f elenart_lnx32.mak

elenavm_lnx32: 
	$(MAKE) -C elenasrc2/elenavm/codeblocks all -f elenavm_lnx32.mak

elenasm_lnx32: 
	$(MAKE) -C elenasrc2/elenasm/codeblocks all -f elenasm.cbp.mak

asm2bin_lnx32: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks all -f asm2bin_lnx32.mak

asm2bin_ppc64le: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks all -f asm2bin_ppc64le.mak

ecv_lnx32: 
	$(MAKE) -C elenasrc2/tools/ecv/codeblocks all -f ecv.cbp.mak

elt_lnx32: 
	$(MAKE) -C elenasrc2/tools/elt/codeblocks all -f elt.cbp.mak

og_lnx32: 
	$(MAKE) -C elenasrc2/tools/og/codeblocks all -f og_lnx32.mak

og_ppc64le: 
	$(MAKE) -C elenasrc2/tools/og/codeblocks all -f og_ppc64le.mak

sg_lnx32: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks all -f sg_lnx32.mak

sg_ppc64le: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks all -f sg_ppc64le.mak

clean_lnx32: clean_elc_lnx32 clean_sg_lnx32 clean_og_lnx32 clean_asm2bin_lnx32 clean_elenart_lnx32 clean_elenavm_lnx32

clean_ppc64le: clean_elc_ppc64le clean_sg_ppc64le

clean_elc_lnx32: 
	$(MAKE) -C elenasrc2/elc/codeblocks clean -f elc_lnx32.mak

clean_elc_ppc64le: 
	$(MAKE) -C elenasrc2/elc/codeblocks clean -f elc_ppc64le.mak

clean_elenart_lnx32: 
	$(MAKE) -C elenasrc2/elenart/codeblocks clean -f elenart_lnx32.mak

clean_elenavm_lnx32: 
	$(MAKE) -C elenasrc2/elenavm/codeblocks clean -f elenavm_lnx32.mak

clean_elenasm_lnx32: 
	$(MAKE) -C elenasrc2/elenasm/codeblocks clean -f elenasm.cbp.mak

clean_asm2bin_lnx32: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks clean -f asm2bin_lnx32.mak

clean_asm2bin_ppc64le: 
	$(MAKE) -C elenasrc2/tools/asm2bin/codeblocks clean -f asm2bin_ppc64le.mak

clean_ecv_lnx32: 
	$(MAKE) -C elenasrc2/tools/ecv/codeblocks clean -f ecv.cbp.mak

clean_elt_lnx32: 
	$(MAKE) -C elenasrc2/tools/elt/codeblocks clean -f elt.cbp.mak

clean_og_lnx32: 
	$(MAKE) -C elenasrc2/tools/og/codeblocks clean -f og_lnx32.mak

clean_sg_lnx32: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks clean -f sg_lnx32.mak

clean_sg_ppc64le: 
	$(MAKE) -C elenasrc2/tools/sg/codeblocks clean -f sg_ppc64le.mak

.PHONY: clean_elc_lnx32 clean_elenart_lnx32 clean_elenavm_lnx32 clean_elenasm_lnx32 clean_asm2bin_lnx32 clean_ecv_lnx32 clean_elt_lnx32 clean_og_lnx32 clean_sg_lnx32
