bin\elc -csrc30\system\system.prj
bin\elc -csrc30\extensions\extensions.prj
bin\elc -cexamples\helloworld\u_helloworld.prj
bin\elc -cexamples\helloworld\helloworld.prj
bin\elc -cexamples\sum\intsum.prj
bin\elc -cexamples\sum\realsum.prj
bin\elc -cexamples\words\words.prj
bin\elc -cexamples\pi\pi.prj
bin\elc -cexamples\bsort\bsort.prj
bin\elc -cexamples\textfile\textfile.prj
bin\elc -cexamples\binary\binary.prj
bin\elc -cexamples\replace\replace.prj
bin\elc -cexamples\goods\goods.prj
bin\elc -cexamples\datetime\dtcalculator.prj
