bin\elc -cexamples\console\helloworld\u_helloworld.prj
bin\elc -cexamples\console\helloworld\helloworld.prj
bin\elc -cexamples\console\sum\intsum.prj
bin\elc -cexamples\console\sum\realsum.prj
bin\elc -cexamples\console\words\words.prj
bin\elc -cexamples\console\pi\pi.prj
bin\elc -cexamples\console\bsort\bsort.prj
bin\elc -cexamples\files\textfile\textfile.prj
bin\elc -cexamples\console\binary\binary.prj
bin\elc -cexamples\console\replace\replace.prj
bin\elc -cexamples\console\goods\goods.prj
bin\elc -cexamples\console\datetime\dtcalculator.prj
bin\elc -cexamples\console\random\random.prj
bin\elc -cexamples\files\textdb\textdb.prj
bin\elc -cexamples\console\matrix\matrix.prj
bin\elc -cexamples\console\trans\tanslit.prj
bin\elc -cexamples\script\interpreter\interpreter.prj
bin\elc -cexamples\script\calculator\calc.prj
bin\elc -cexamples\gui\agenda\agenda.prj
bin\elc -cexamples\gui\graphs\graphs.prj
bin\elc -cexamples\gui\c_a_g\c_area_gui.prj
rem bin\elc -cexamples\gui\notepad\notepad.prj
bin\elc -cexamples\db\sqlite\sqlite_test.prj
bin\elc -cexamples\console\pi2\pi2.prj
bin\elc -cexamples\net\chat\chatserver.prj
bin\elc -cexamples\net\chat\chat.prj
