bin\elc examples\console\helloworld\u_helloworld.prj
bin\elc examples\console\helloworld\helloworld.prj
bin\elc examples\console\sum\intsum.prj
bin\elc examples\console\sum\realsum.prj
bin\elc examples\console\words\words.prj
bin\elc examples\console\pi\pi.prj
bin\elc examples\console\bsort\bsort.prj
bin\elc examples\files\textfile\textfile.prj
bin\elc examples\console\binary\binary.prj
bin\elc examples\console\replace\replace.prj
bin\elc examples\console\goods\goods.prj
bin\elc examples\console\datetime\dtcalculator.prj
bin\elc examples\console\random\random.prj
bin\elc examples\files\textdb\textdb.prj
bin\elc examples\console\trans\tanslit.prj
bin\elc examples\console\matrix\matrix.prj
bin\elc examples\script\interpreter\interpreter.prj
bin\elc examples\script\calculator\calc.xprj
bin\elc examples\script\calculator\calc.prj
bin\elc examples\script\js\vmconsole.prj
bin\elc examples\script\js\fibonacci.xprj 
bin\elc examples\gui\agenda\agenda.prj
bin\elc examples\gui\graphs\graphs.prj
bin\elc examples\gui\c_a_g\c_area_gui.prj
rem bin\elc examples\gui\notepad\notepad.prj
bin\elc examples\db\sqlite\sqlite_test.prj
bin\elc examples\console\pi2\pi2.prj
bin\elc examples\net\chat\chatserver.prj
bin\elc examples\net\chat\chat.prj
bin\elc examples\gui\helloworld\xforms_hellowindow.prj
rem bin\elc examples\gui\helloworld\xforms_hellowindow.xprj
bin\elc tests\system\system_test.prj
bin\elc examples\script\live\live.prj 
