/// Attributes
//T               = #16390.
//V               = #30.
//
//type            = #16390.
#16386 = class;
//struct          = #8197.
//symbol          = #16389.
//constructor     = #16384.
//enum            = #8198.
//sealed          = #8195.
//embeddable      = #8193.
//template        = #16391.
//extension       = #8203.
//
//const           = #8201.
//singleton       = #8208.
//generic         = #8202.
//static          = #8194.
//var             = #16385.
//auto            = #50.
//interface       = #8196.
//field           = #16392.
//method          = #16393.
//__loop          = #16394.
////nonstructural   = #8204.
//import          = #16395.
//__extern        = #16396.
//closure         = #8205.
//mixin           = #8206.
//__accessor      = #16399.
//__block         = #16400.
//__nested        = #16401.
//preloaded       = #8207.
//cast            = #16387.
//set             = #16402.  
//
//abstract        = #8210. 
#8211  = public;
//private         = #8212.
#8213  = internal;
//closed          = #8214.
//predefined      = #8215.
//dispatch        = #8216.
//
//__args          = #32. 
//
//__string        = #8200.
//__int           = #11.
//__ptr           = #12.
//__real          = #15.
//__dword         = #16.
//__mssg          = #19.
//__subj          = #18.
//__extmssg       = #21.
////__tape_mixin    = #8209.
//__symbol        = #22.
//dynamic         = #30.
//stackunsafe     = #16403.
//
//__ifoperator    = #4097.
//__ifnotoperator = #4098.
//
///// Provides classes that describe the basic functionality
//
//type object     = system'Object.
//
//// === basic logical types ===
//type bool       = system'BoolValue.
//
//// === basic type aliases ===
//type byte       = system'ByteNumber.
//type short      = system'ShortNumber.
//type int        = system'IntNumber.
//type uint       = system'UIntNumber.
//type long       = system'LongNumber.
//type real       = system'RealNumber.
//type char       = system'CharValue.
//type mssg       = system'Message.
////type ext_mssg   = system'ExtensionMessage.
//type literal    = system'LiteralValue.
//type wide       = system'WideLiteralValue.
//type handle     = system'Handle.
//type rt_ptr     = system'RTPointer.
//type dirty_ptr  = system'UnsafePointer.
