..\..\bin\elc -caccumulator\accumulator.prj
..\..\bin\elc -cackermann\ackerman.prj
..\..\bin\elc -caddfield\addfield.prj
..\..\bin\elc -canonymrec\anonymrec.prj
..\..\bin\elc -caplusb\aplusb.prj
..\..\bin\elc -capplycallback\arraycallback.prj
..\..\bin\elc -carithmeticint\arithmeticint.prj
..\..\bin\elc -carithmmean\arithmmean.prj
..\..\bin\elc -carrayconcat\arrayconcat.prj
..\..\bin\elc -carraymode\arraymode.prj
..\..\bin\elc -carrays\arrays.prj
..\..\bin\elc -cassociativearrays\associativearrays.prj
..\..\bin\elc -cbestshuffle\bestshuffle.prj
..\..\bin\elc -cbinary\binary.prj
..\..\bin\elc -camb\amb.prj
..\..\bin\elc -cbitwise\bitwise.prj
..\..\bin\elc -cbrackets\brackets.prj
..\..\bin\elc -canagram\anagram.prj
..\..\bin\elc -cmedian\median.prj
..\..\bin\elc -csmavg\smavg.prj
..\..\bin\elc -ccaesar\caesar.prj
..\..\bin\elc -ccharmatch\charmatch.prj
..\..\bin\elc -carithmeval\arithmeval.prj
..\..\bin\elc -ccombinations\combinations.prj
..\..\bin\elc -cbullscows\bullscows.prj
..\..\bin\elc -ccalendar\calendar.prj
..\..\bin\elc -cdoors\doors.prj
..\..\bin\elc -ctwentyfour\twentyfour.prj
..\..\bin\elc -csimple_windowed_app\simple_windowed_app.prj
..\..\bin\elc -cgui_component_interaction\gui_component_interaction.prj
..\..\bin\elc -cstring_append\string_append.prj
..\..\bin\elc -cstring_case\string_case.prj
..\..\bin\elc -cstring_comparison\string_comparison
..\..\bin\elc -cstring_concatenation\string_concatenation.prj
..\..\bin\elc -cstring_interpolation\string_interpolation.prj
..\..\bin\elc -cstring_matching\string_matching.prj
..\..\bin\elc -cstring_prepend\string_prepend.prj