..\..\bin\elc accumulator\accumulator.prj
..\..\bin\elc ackermann\ackerman.prj
..\..\bin\elc addfield\addfield.prj
..\..\bin\elc anonymrec\anonymrec.prj
..\..\bin\elc aplusb\aplusb.prj
..\..\bin\elc applycallback\arraycallback.prj
..\..\bin\elc arithmeticint\arithmeticint.prj
..\..\bin\elc arithmmean\arithmmean.prj
..\..\bin\elc arrayconcat\arrayconcat.prj
..\..\bin\elc arraymode\arraymode.prj
..\..\bin\elc arrays\arrays.prj
..\..\bin\elc associativearrays\associativearrays.prj
..\..\bin\elc bestshuffle\bestshuffle.prj
..\..\bin\elc binary\binary.prj
..\..\bin\elc amb\amb.prj
..\..\bin\elc bitwise\bitwise.prj
..\..\bin\elc brackets\brackets.prj
..\..\bin\elc anagram\anagram.prj
..\..\bin\elc median\median.prj
..\..\bin\elc smavg\smavg.prj
..\..\bin\elc caesar\caesar.prj
..\..\bin\elc charmatch\charmatch.prj
..\..\bin\elc arithmeval\arithmeval.prj
..\..\bin\elc combinations\combinations.prj
..\..\bin\elc bullscows\bullscows.prj
..\..\bin\elc calendar\calendar.prj
..\..\bin\elc doors\doors.prj
..\..\bin\elc twentyfour\twentyfour.prj
..\..\bin\elc simple_windowed_app\simple_windowed_app.prj
..\..\bin\elc gui_component_interaction\gui_component_interaction.prj
..\..\bin\elc string_append\string_append.prj
..\..\bin\elc string_case\string_case.prj
..\..\bin\elc string_comparison\string_comparision.prj
..\..\bin\elc string_concatenation\string_concatenation.prj
..\..\bin\elc string_interpolation\string_interpolation.prj
..\..\bin\elc string_matching\string_matching.prj
..\..\bin\elc string_prepend\string_prepend.prj
..\..\bin\elc ninetynine\ninetynine.prj
..\..\bin\elc evolutionary\evolutionary.prj
..\..\bin\elc compare_str_list\complist.prj
..\..\bin\elc dynamic_var\dynamic_var.prj
..\..\bin\elc firstclass\firstclass.prj
..\..\bin\elc loop_multiple_arrays\loopma.prj
..\..\bin\elc knutalg\knutalg.prj
..\..\bin\elc manboy\manboy.prj
..\..\bin\elc reverse_words_in_string\rev_words.prj
..\..\bin\elc tokenizer\tokenizer.prj
..\..\bin\elc trigonometric\trigonometric.prj
..\..\bin\elc toppergroup\toppergroup.prj
..\..\bin\elc twelvestats\twelvestats.prj
..\..\bin\elc truncprime\truncprime.prj
..\..\bin\elc treeview\treeview.prj
..\..\bin\elc gameoflife\gameoflife.prj
..\..\bin\elc zhangsuen\zhangsuen.prj
..\..\bin\elc zeckendorf\zeckendorf.prj
..\..\bin\elc zeckendorf_arithm\zeckendorf_arithm.prj 
..\..\bin\elc ycombinator\ycombinator.prj
