#!/bin/bash

if [ "$(id -u)" -ne 0 ]
then
  SUDO=sudo
else
  SUDO=
fi

mkdir -p ../../lib60
mkdir -p ../../bin/x32

echo compiling data files

../../bin/sg-cli ../../dat/sg/syntax67.txt
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

# ../bin/elena-og ../dat/og/rules.txt
# ret=$?
# if [ $ret -eq 0 ]
# then
#   echo .
# else
#   echo "Failure" >&2
#   exit 1
# fi

../../bin/og-cli ../../dat/og/bc_rules60.txt
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

../../bin/og-cli -s ../../dat/og/bt_rules60.txt
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

../../bin/og-cli -s ../../dat/og/bt_xrules60.txt
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

cp ../../dat/og/*.dat ../../bin
cp ../../dat/sg/syntax60.dat ../../bin
cp ../../dat/sg/syntax67.dat ../../bin

echo compiling assembly files

../../bin/asm-cli -linux -x86 ../../asm/x32/core60.asm ../../bin/x32 core60_lnx.bin
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

../../bin/asm-cli -linux -x86 ../../asm/x32/corex60.asm ../../bin/x32 corex60_lnx.bin
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

../../bin/asm-cli -linux -x86 ../../asm/x32/core60_client.asm ../../bin/x32 core60_lnx_client.bin
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

echo installing binaries and configuration

$SUDO mkdir -p /usr/share/elena
$SUDO mkdir -p /etc/elena/
$SUDO mkdir -p /etc/elena/templates/
$SUDO mkdir -p /etc/elena/scripts/
$SUDO mkdir -p /usr/lib/elena/core/x32/
$SUDO mkdir -p /usr/lib/elena/lib60

$SUDO cp --remove-destination ../../bin/libelenart60.so /usr/lib/elena/
$SUDO cp --remove-destination ../../bin/libelenasm60.so /usr/lib/elena/
$SUDO cp --remove-destination ../../bin/libelenavm60.so /usr/lib/elena/
$SUDO cp --remove-destination ../../bin/elena-cli /usr/bin/

$SUDO ldconfig /usr/lib/elena

$SUDO cp --remove-destination ../../bin/elc60.config /etc/elena/
$SUDO cp --remove-destination ../../bin/elenart60.config /etc/elena/
$SUDO cp --remove-destination ../../bin/elenavm60.config /etc/elena/
$SUDO cp --remove-destination ../../bin/elt60.es /etc/elena/
$SUDO cp --remove-destination ../../bin/templates/*.config /etc/elena/templates/
$SUDO cp --remove-destination ../../bin/scripts/*.es /etc/elena/scripts/
$SUDO cp --remove-destination ../../bin/scripts/*.elt /etc/elena/scripts/

$SUDO cp --remove-destination ../../dat/og/*.dat /usr/share/elena/
$SUDO cp --remove-destination ../../dat/sg/syntax60.dat /usr/share/elena
$SUDO cp --remove-destination ../../dat/sg/syntax67.dat /usr/share/elena

$SUDO cp --remove-destination ../../bin/x32/core60_lnx.bin /usr/lib/elena/core/x32/
$SUDO cp --remove-destination ../../bin/x32/corex60_lnx.bin /usr/lib/elena/core/x32/
$SUDO cp --remove-destination ../../bin/x32/core60_lnx_client.bin /usr/lib/elena/core/x32/

echo compiling lib60 files

 ../../bin/asm-cli -bc32 ../../src60/core/system.core_routines.esm ../../lib60
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi

 ../../bin/elena-cli ../../src60/elena_api.linux.prjcol
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 $SUDO cp --remove-destination ../../lib60/*.nl /usr/lib/elena/lib60
 $SUDO cp --remove-destination ../../lib60/*.dnl /usr/lib/elena/lib60

 elena-cli ../../tests60/system_tests/system_tests.prj
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 ../../tests60/system_tests/system_tests
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi
