#!/bin/bash

if [ "$(id -u)" -ne 0 ]
then
  SUDO=sudo
else
  SUDO=
fi

mkdir -p ../../lib60_win
mkdir -p ../../bin/x32

echo compiling assembly files

../../bin/asm-cli -windows -x86 ../../asm/x32/core60.asm ../../bin/x32 core60_win.bin
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

../../bin/asm-cli -windows -x86 ../../asm/x32/corex60.asm ../../bin/x32 corex60_win.bin
ret=$?
if [ $ret -eq 0 ]
then
  echo .
else
  echo "Failure" >&2
  exit 1
fi

echo installing binaries

$SUDO mkdir -p /usr/lib/elena/core/x32/
$SUDO mkdir -p /usr/lib/elena/lib60_win

$SUDO cp --remove-destination ../../bin/elena-cli /usr/bin/

$SUDO cp --remove-destination ../../bin/x32/core60_win.bin /usr/lib/elena/core/x32/
$SUDO cp --remove-destination ../../bin/x32/corex60_win.bin /usr/lib/elena/core/x32/

echo compiling lib60 files

 ../../bin/asm-cli -bc32 ../../src60/core/system.core_routines.esm ../../lib60_win
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi

 ../../bin/elena-cli -xtwin32 ../../src60/elena_api.linux.prjcol
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 $SUDO cp --remove-destination ../../lib60_win/*.nl /usr/lib/elena/lib60_win
 $SUDO cp --remove-destination ../../lib60_win/*.dnl /usr/lib/elena/lib60_win

 $SUDO cp --remove-destination ../../bin/winstub.ex_ /usr/share/elena
