#!/bin/bash

 ../../bin/elena-cli ../../tests60/system_tests/system_tests.prj
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 ../../tests60/system_tests/system_tests
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi

 ../../bin/elena-cli ../../tests60/mta_tests/mta_tests.prj
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 # Keep an external watchdog for deadlocks involving the whole process.
 timeout --signal=KILL 300s ../../tests60/mta_tests/mta_tests
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi

 ../../bin/elena-cli ../../tests60/async_tests/async_tests.prj
 ret=$?
 if [ $ret -eq 1 ]
 then
   echo "Failure" >&2
   exit 1
 else
   echo .
 fi

 timeout --signal=KILL 300s ../../tests60/async_tests/async_tests
 ret=$?
 if [ $ret -eq 0 ]
 then
   echo .
 else
   echo "Failure" >&2
   exit 1
 fi
