#!/bin/bash

if [ "$(id -u)" -ne 0 ]
then
  SUDO=sudo
else
  SUDO=
fi

read -p "You are going to uninstall ELENA Language. Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

  echo removing ELENA shared libraries
  $SUDO rm -f /usr/lib/elena/libelenart60.so
  $SUDO rm -f /usr/lib/elena/libelenasm60.so
  $SUDO rm -f /usr/lib/elena/libelenavm60.so

  echo removing ELENA compiler executable
  $SUDO rm -f /usr/bin/elena-cli

  echo removing ELENA configuration files

  $SUDO rm -f /etc/elena/templates/*.config
  $SUDO rmdir --ignore-fail-on-non-empty /etc/elena/templates

  $SUDO rm -f /etc/elena/scripts/*.es
  $SUDO rm -f /etc/elena/scripts/*.elt
  $SUDO rmdir --ignore-fail-on-non-empty /etc/elena/scripts

  $SUDO rm -f /etc/elena/*.config
  $SUDO rm -f /etc/elena/*.es
  $SUDO rmdir --ignore-fail-on-non-empty /etc/elena

  echo removing ELENA data files
  $SUDO rm -f /usr/share/elena/*.dat
  $SUDO rmdir --ignore-fail-on-non-empty /usr/share/elena

  echo removing ELENA API compiled modules

  $SUDO rm -f /usr/lib/elena/core/x32/*.bin
  $SUDO rmdir --ignore-fail-on-non-empty /usr/lib/elena/core/x32
  $SUDO rmdir --ignore-fail-on-non-empty /usr/lib/elena/core

  $SUDO rm -f /usr/lib/elena/lib60/*.nl
  $SUDO rm -f /usr/lib/elena/lib60/*.dnl

  $SUDO rmdir --ignore-fail-on-non-empty /usr/lib/elena/lib60
  $SUDO rmdir --ignore-fail-on-non-empty /usr/lib/elena

fi

exit 0
