//import extensions'dynamic;
//
//static escriptEngine
//    = new ScriptEngine()            
//            .loadPath("~\scripts\assembly.es")
//            .loadPath("~\scripts\escript.es");
//
//public singleton escript
//{
//    eval(string script)
//        = TapeAssembly.load(escriptEngine.eval:script).eval();
//            
//    load(string path)
//        = TapeAssembly.load(escriptEngine.loadPath:path).eval();
//}