extension(space) spaceOp
{
//    run &ruleset:set
//    [
//        self scan:set &cellfunc: (:o &space:space &int:x &int:y)
//            [ 
//                int cell := 0.
//                (o ruleset validate &space:space &int:x &int:y)
//                    ? [ cell := 1. ]
//                    ! [ cell := 0. ].
//                                
//                space setAt &int:x &int:y &int:cell.
//            ].
//    ]
}