// data structure wrappers
#subject(class:system'winforms'HInstance)         hinstance.
#subject(class:system'winforms'WindowHandle)      hwnd.

#subject(class:system'winforms'MSG)               win_msg.
#subject(class:system'winforms'CREATESTRUCT)      win_createstruct.
#subject(class:system'winforms'RECT)              win_rect.

#subject(class:system'winforms'WindowCallback)    win_callback.
#subject(class:system'winforms'WindowListener)    win_listener.
