
public program()
{
//    console;
//    console.write("abc"w)

    byte buffer[128];
    
    var b := buffer;
    var l := b.Length

//            var literal := "abc"w;
//            byte buffer[256];
//            //int  length := 3;
//            int  index := 0;
//            int  buf_len := 256;
//            int  subs_len := 3;
//
//                //subs_len := /*length < 128 ? *//*length*/3/* : 128*/;
//                
//                system'text'OEMEncoder.convert(index, ref subs_len, literal, buffer, ref buf_len);

}

startUp = program();
