#define system.

#subject(class:system'IntNumber)year.
#subject(class:system'IntNumber)month.
#subject(class:system'IntNumber)day.
#subject(class:system'IntNumber)hour.
#subject(class:system'IntNumber)second.
#subject(class:system'IntNumber)millisecond.
#subject(class:system'IntNumber)years.
#subject(class:system'IntNumber)months.
#subject(class:system'IntNumber)days.
#subject(class:system'IntNumber)hours.
#subject(class:system'IntNumber)seconds.
#subject(class:system'LongNumber)milliseconds.