# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Nightly MacOS AMD64 Build

on:
  workflow_dispatch: # Put here!!

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-15-intel]
        platform: [amd64]
 
    steps:
    - uses: actions/checkout@v4
      with:
        ref: iteration47

    - name: Set version
      run: |
        VER=$(cat VERSION)
        echo "BUILD_TAG=$VER" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        brew install llvm
        brew install lld

    - name: Build
      run: |
        make all_mac_${{ matrix.platform }}
        cd scripts/mac.${{ matrix.platform }}
        ./local_build_package_amd64.script
        ./local_create_package.script
          
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: nightly
        assets: '*amd64-mac.tar.xz'
        fail-if-no-assets : false

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        draft: false
        prerelease: true
        files: |
          ./build/*.tar.xz
