# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Linux Make Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Put here!!

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [amd64]
 
    steps:
    - uses: actions/checkout@v4

    - name: Set version
      run: |
        VER=$(cat VERSION)
        echo "BUILD_TAG=$VER" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get install -y gcc-11 g++-11

    - name: Build
      run: make all_${{ matrix.platform }}
