# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Linux Make Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Put here!!

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [i386, amd64]
 
    steps:
    - uses: actions/checkout@v4

    - name: Set version
      run: |
        VER=$(cat VERSION)
        echo "BUILD_TAG=$VER" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential gcc-multilib g++-multilib alien dpkg-dev debhelper

    - name: Build
      run: make all_${{ matrix.platform }}

    - name: Generate Data / API
      run: |
        cd scripts/${{ matrix.platform }}
        sudo ./local_build_package_${{ matrix.platform }}.script 

    - name: Run functional test
      run: |
        cd scripts/${{ matrix.platform }}
        ./local_runtests.script

    - name: Create a package
      run: |
        cd scripts/${{ matrix.platform }}
        ./local_create_package.script
