# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Put here!!

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\elenasrc3\elenasrc3.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        platform: [x86, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v2

    - name: Restore nuget packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
 
    - name: Set version
      run: |
        VER=$(cat VERSION)
        echo "BUILD_TAG=$VER" >> $GITHUB_ENV

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:platform=${{ matrix.platform }} /m:2

    - name: Generate Data
      shell: cmd
      run: scripts\rebuild_data60_${{matrix.platform}}.bat

    - name: Run Tests
      shell: cmd
      run: bin\elena-tests-${{matrix.platform}}.exe

    - name: Compile Lib
      shell: cmd
      run: scripts\rebuild_lib60_${{matrix.platform}}.bat

    - name: Prepare Release
      shell: cmd
      run: scripts\create_package_${{matrix.platform}}.bat 
        
    - run: Compress-Archive .\build\${{matrix.platform}}\* .\build\elena-lang-${{matrix.platform}}-${{ env.BUILD_TAG }}.zip
          
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.BUILD_TAG }}
        draft: false
        prerelease: true
        files: |
          ./build/*.zip
